### ISSUE TITLE
Call of calcGDPpc

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/mrwaste#3]
Does this actually work? Because it shouldn't really ;) if it does, are you using an older version of mrdriver? Or is this function deprecated?
https://github.com/pik-piam/mrwaste/blob/8b9f4b43a0e2f07f2d9d5b294cc228e5cff8c485/R/calcWasteGen.R#L13

The correct call should be:
`calcOutput("GDPpc", scenario = "SSPs", naming = "scenario", aggregate = FALSE)`
(The scenario argument specifies which scenarios you would like, in this case the 5 SSP scenarios, and the naming argument tells calcGDPpc to return a magpie object with only the "scenario" as variable names, i.e. "SSPx", in contrast to "indicator_scenario" which returns "gdppc_SSPx" - the default for now...)

**Comment by caviddhen** [comment]
Hey, funny you're digging around in there. This package is a bit deprecated. it's more of a standalone for a paper from some years ago now. Do you need it to be changed? I have a hunch many parts of this package might not work perfectly at the moment, pending necessity for an overhaul...

**Comment by johanneskoch94** [comment]
Gotcha :+1: Yeah I'm thinking of improving some default behavior of mrdrivers functions, and am trying to make sure that no packages break because of any changes ;) This popped up when I searched through our R-packages...

**Comment by johanneskoch94** [comment]
Fixed by a93a1c0
